GroupProject/GroupProject/Pages/CallInSick.cshtml.cs
using BussinessLayer.Controllers;
using BussinessLayer.Controllers.Shifts;
using ClassLibrary.Classes;
using ClassLibrary.Controllers;
using DataAccessLayer;
using DataAccessLayer.DAL;
using DataItems.LogicItems;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWebsite.Pages
{
    public class CallInSickModel : PageModel
    {
        public Shift _selectedShift;
		[BindProperty]
		public string _reason { get; set; }
        private ShiftController _shiftController;
		private EmployeeController _employeeController;

		public CallInSickModel()
		{
            _shiftController = new(new DALShiftController());
			_employeeController = new(new DALEmployeeController());
		}
        public void OnGet(int id)
        {
			_selectedShift = _shiftController.GetById(id);
		}
        public IActionResult OnPost(int shiftId)
        {
            CancelledShift cancelledShift = new CancelledShift
            {
                AssignedEmployee = _employeeController.Get(HttpContext.Session.GetString("username")),
                Shift = _shiftController.GetById(shiftId),
                Reason = _reason
            };

            CancelledShiftController cancelledShiftController = new(new DALCancelledShiftController());
            cancelledShiftController.Add(cancelledShift, new DALShiftController());

            return RedirectToPage("Index");
        }
    }
}

GroupProject/GroupProject/Pages/CancelledShifts.cshtml.cs
using BussinessLayer.Controllers;
using ClassLibrary.Classes;
using ClassLibrary.Controllers;
using ClassLibrary.Interfaces;
using DataAccessLayer;
using DataAccessLayer.DAL;
using DataItems.LogicItems;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Net.Http.Headers;
using System.Security.Cryptography.Xml;

namespace MediaBazaarWebsite.Pages
{
	public class CancelledShiftsModel : PageModel
	{
		VacationController _vacationController;
		[BindProperty]
		public Vacation[] _vacations { get; set; }

		[BindProperty]
		public List<CancelledShift> shifts { get; set; }

		[BindProperty]
		public List<Vacation> vacations { get; set; }

		public static string[] ShiftFilters = new string[2] { "Descending", "AllShifts" };
		public static string[] VacationFilters = new string[2] { "StartDescending", "AllVacations" };

		Employee _loggedInEmployee;
		EmployeeController _employeeController;
		public CancelledShiftsModel()
		{
			_employeeController = new(new DALEmployeeController());
			_vacationController = new(new DALVacationController());
		}
		public void OnGet()
		{
			_loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));

			_vacations = _vacationController.ReadAllByMember(_loggedInEmployee.Id);

			vacations = _vacations.OrderByDescending(Vacation => Vacation.StartDate).ToList();
		}

		public void OnPostFilter(string filter)
		{
			switch (filter)
			{
				case "Ascending":
					{
						ShiftFilters[0] = filter;
						break;
					}
				case "Descending":
					{
						ShiftFilters[0] = filter;
						break;
					}
				case "Sent":
					{
						ShiftFilters[1] = filter;
						break;
					}
				case "Viewed":
					{
						ShiftFilters[1] = filter;
						break;
					}
				case "AllShifts":
					{
						ShiftFilters[1] = filter;
						break;
					}
				case "ClearShifts":
					{
						ShiftFilters[0] = "Descending";
						ShiftFilters[1] = "AllShifts";
						break;
					}
				case "StartAscending":
					{
						VacationFilters[0] = filter;
						break;
					}
				case "StartDescending":
					{
						VacationFilters[0] = filter;
						break;
					}
				case "EndAscending":
					{
						VacationFilters[0] = filter;
						break;
					}
				case "EndDescending":
					{
						VacationFilters[0] = filter;
						break;
					}
				case "Approved":
					{
						VacationFilters[1] = filter;
						break;
					}
				case "Pending":
					{
						VacationFilters[1] = filter;
						break;
					}
				case "Rejected":
					{
						VacationFilters[1] = filter;
						break;
					}
				case "AllVacations":
					{
						VacationFilters[1] = filter;
						break;
					}
				case "ClearVacations":
					{
						VacationFilters[0] = "StartDescending";
						VacationFilters[1] = "AllVacations";
						break;
					}
			}
			OnPost();
		}

		public IActionResult OnPost()
		{
			_loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));

			_vacations = _vacationController.ReadAllByMember(_loggedInEmployee.Id);

			if (VacationFilters[0] == "StartAscending")
			{
				_vacations = _vacations.OrderBy(Vacation => Vacation.StartDate).ToArray();

				if (VacationFilters[1] == "Approved")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Pending")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Pending == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Rejected")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == false && vacation.Pending == false)
						{
							vacations.Add(vacation);
						}
					}
				}
				else
				{
					vacations = _vacations.ToList();
				}


			}
			else if (VacationFilters[0] == "StartDescending")
			{
				_vacations = _vacations.OrderByDescending(Vacation => Vacation.StartDate).ToArray();

				if (VacationFilters[1] == "Approved")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Pending")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Pending == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Rejected")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == false && vacation.Pending == false)
						{
							vacations.Add(vacation);
						}
					}
				}
				else
				{
					vacations = _vacations.ToList();
				}
			}
			else if (VacationFilters[0] == "EndAscending")
			{
				_vacations = _vacations.OrderBy(Vacation => Vacation.EndDate).ToArray();

				if (VacationFilters[1] == "Approved")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Pending")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Pending == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Rejected")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == false && vacation.Pending == false)
						{
							vacations.Add(vacation);
						}
					}
				}
				else
				{
					vacations = _vacations.ToList();
				}
			}
			else if (VacationFilters[0] == "EndDescending")
			{
				_vacations = _vacations.OrderByDescending(Vacation => Vacation.EndDate).ToArray();

				if (VacationFilters[1] == "Approved")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Pending")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Pending == true)
						{
							vacations.Add(vacation);
						}
					}
				}
				else if (VacationFilters[1] == "Rejected")
				{
					foreach (var vacation in _vacations)
					{
						if (vacation.Approved == false && vacation.Pending == false)
						{
							vacations.Add(vacation);
						}
					}
				}
				else
				{
					vacations = _vacations.ToList();
				}
			}
			return Page();
		}
	}
}

GroupProject/GroupProject/Pages/ChangeDetails.cshtml.cs
using BussinessLayer.Controllers;
using ClassLibrary.Classes;
using ClassLibrary.Controllers;
using DataAccessLayer.DAL;
using DataItems.LogicItems;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWebsite.Pages
{
    public class ChangeDetails : PageModel
    {
		public Employee _loggedInEmployee;
		private EmployeeController _employeeController;

		public string _username { get; set; }
        public string _email { get; set; }
        public string _phone { get; set; }
        public string _profilePicture { get; set; }
        public ChangeDetails()
        {
			_employeeController = new(new DALEmployeeController());
		}
		public void OnGet()
        {
			if (HttpContext.Session.GetString("username") != null)
			{
				_loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));
			}
		}
    }
}

GroupProject/GroupProject/Pages/ChooseShift.cshtml.cs
using BussinessLayer.Controllers;
using BussinessLayer.Controllers.Shifts;
using ClassLibrary.Classes;
using ClassLibrary.Controllers;
using DataAccessLayer;
using DataAccessLayer.DAL;
using DataItems.LogicItems;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWebsite.Pages
{
    public class ChooseShiftModel : PageModel
    {
        CancelledShiftController _cancelledShiftController;
        ShiftController _shiftController;
        [BindProperty]
        public CancelledShift[] _cancelledShifts { get; set; }

        [BindProperty]
        public Vacation[] _vacations { get; set; }

        [BindProperty]
        public List<CancelledShift> shifts { get; set; }

        [BindProperty]
        public List<Vacation> vacations { get; set; }

        public static string[] ShiftFilters = new string[2] { "Descending", "AllShifts" };
        public static string[] VacationFilters = new string[2] { "StartDescending", "AllVacations" };
        Employee _loggedInEmployee;
        EmployeeController _employeeController;

        [BindProperty]
        public int Id { get; set; } = 0;

        public ChooseShiftModel()
        {
            _employeeController = new(new DALEmployeeController());
            _cancelledShiftController = new(new DALCancelledShiftController());
            _shiftController = new(new DALShiftController());
        }
        public IActionResult OnGet(int id)
        {
            _loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));

            Id = id;

            _cancelledShifts = _cancelledShiftController.GetFromVacation(Id);

            return Page();
        }

        public IActionResult OnPost(int id, int shiftId)
        {
            _loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));

            Id = id;

            CancelledShift cancelledShift = _cancelledShiftController.GetById(shiftId);
            cancelledShift.NewEmployee = _loggedInEmployee;
            
            Shift shift = _shiftController.GetById(cancelledShift.Shift.Id);
            shift.IsCancelled = false;
            shift.Employee = _loggedInEmployee;

            _shiftController.Update(shift);
            _cancelledShiftController.Update(cancelledShift);

            _cancelledShifts = _cancelledShiftController.GetFromVacation(Id);

            return Page();
        }
    }
}

GroupProject/GroupProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace GroupProject.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

GroupProject/GroupProject/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer;
using DataAccessLayer.DAL;
using DataItems.LogicItems;
using BussinessLayer.Controllers;
using BussinessLayer.Controllers.Shifts;

namespace GroupProject.Pages
{
    public class HomeModel : PageModel
    {
        public Employee _loggedInEmployee;
        private EmployeeController _employeeController;
        private ShiftController _shiftController;
        private AnnouncemetsController _announcemetsController;
		[BindProperty]
		public Shift[] _assignedShifts { get; set; }
        [BindProperty]
        public Announcements[] _announcements { get; set; }

        public List<int> shiftIdsToCancel = new();

        public HomeModel()
        {
			_employeeController = new(new DALEmployeeController());
			_shiftController = new(new DALShiftController());
            _announcemetsController = new(new DALAnnouncementsController());
		}

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                _loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));
            }
            else
            {
				return RedirectToPage("Login");
            }

            _assignedShifts = _shiftController.GetFutureShiftsByEmp(_loggedInEmployee);
            _assignedShifts = _assignedShifts.OrderBy(shift => shift.Date).ToArray();

            shiftIdsToCancel = _shiftController.GetShiftIdsToCancelByEmp(_loggedInEmployee, _assignedShifts);

            _announcements = _announcemetsController.GetAllCurrent();

            return Page();

        }
    }
}

GroupProject/GroupProject/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWebsite.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("Login");
        }
    }
}

GroupProject/GroupProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GroupProject.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

GroupProject/GroupProject/Pages/Shifts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Reflection;
using DataAccessLayer.DAL;
using DataItems.LogicItems;
using BussinessLayer.Controllers;
using BussinessLayer.Controllers.Shifts;

namespace GroupProject.Pages
{
    public class Shifts : PageModel
    {
        public Employee _loggedInEmployee;
        private EmployeeController _employeeController;
        private ShiftController _shiftController;
        public Shift[] _assignedShifts;
		private readonly EmployeeController employeeController = new EmployeeController(new DALEmployeeController());
		private readonly ShiftController shiftController = new ShiftController(new DALShiftController());
		public List<string> WeekDays { get; set; } = new List<string> { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
        public DateTime CurrentDate { get; set; } = DateTime.Today;
        public DateTime NewDate { get; set; }
        public List<int> shiftIdsToCancel = new();

        private static int counter = 0;
		
		public Shifts()
		{
			_employeeController = new(new DALEmployeeController());
			_shiftController = new(new DALShiftController());
            NewDate = CurrentDate;
        }

		public IActionResult OnGet()
		{
            if (HttpContext.Session.GetString("username") != null)
            {
                _loggedInEmployee = _employeeController.Get(HttpContext.Session.GetString("username"));
            }
            else
            {
                return RedirectToPage("Login");
            }
            _assignedShifts = _shiftController.GetAllAssigned(_loggedInEmployee);
			shiftIdsToCancel = _shiftController.GetShiftIdsToCancelByEmp(_loggedInEmployee, _assignedShifts);

			return Page();
		}

		public void OnPostPreviousWeek()
		{
            counter--;
            NewDate = CurrentDate.AddDays(counter * 7);
            CurrentDate = NewDate;

            if (HttpContext.Session.GetString("username") != null)
            {
                _loggedInEmployee = employeeController.Get(HttpContext.Session.GetString("username"));
            }
            _assignedShifts = _shiftController.GetAllAssigned(_loggedInEmployee);
            shiftIdsToCancel = _shiftController.GetShiftIdsToCancelByEmp(_loggedInEmployee, _assignedShifts);


        }

        public void OnPostCurrentWeek()
        {
            counter = 0;
            NewDate = CurrentDate;

            if (HttpContext.Session.GetString("username") != null)
            {
                _loggedInEmployee = employeeController.Get(HttpContext.Session.GetString("username"));
            }
            _assignedShifts = _shiftController.GetAllAssigned(_loggedInEmployee);
            shiftIdsToCancel = _shiftController.GetShiftIdsToCancelByEmp(_loggedInEmployee, _assignedShifts);

        }

        public void OnPostNextWeek() 
		{
            counter++;
            NewDate = CurrentDate.AddDays(counter * 7);
            CurrentDate = NewDate;

            if (HttpContext.Session.GetString("username") != null)
            {
                _loggedInEmployee = employeeController.Get(HttpContext.Session.GetString("username"));
            }
            _assignedShifts = _shiftController.GetAllAssigned(_loggedInEmployee);
            shiftIdsToCancel = _shiftController.GetShiftIdsToCancelByEmp(_loggedInEmployee, _assignedShifts);

        }
    }
}

GroupProject/GroupProject/Pages/ChangeDetails.cshtml
@page
@model MediaBazaarWebsite.Pages.ChangeDetails
@{
	ViewData["Title"] = "Change details";
}
<div class="container">
	<h1 class="mt-2 mb-2 text-center">Changing details</h1>
	<div class="row text-center m-2 mb-1 justify-content-center">
		<div class="col-4">
			<div class="card bg-light mt-4" style="width: 100%;">
				<div class="card-body">

					<div class="row">
						<div class="col-4">
							<p>Profile pictures:</p>
						</div>
						<div class="col-4">
							<input type="text" asp-for="_profilePicture" placeholder="Type your username..." class="inputs">
						</div>
					</div>
					<div class="row">
						<div class="col-4">
							<p>Username:</p>
						</div>
						<div class="col-4">
							<input type="text" asp-for="_username" placeholder="Type your username..." class="inputs">
						</div>
					</div>
					<div class="row m-2">
						<div class="col-4">
							<p>Email:</p>
						</div>
						<div class="col-4">
							<input type="text" asp-for="_email" placeholder="Type your username..." class="inputs">
						</div>
					</div>
					<div class="row m-2">
						<div class="col-4">
							<p>Phone:</p>
						</div>
						<div class="col-4">
							<input type="text" asp-for="_phone" placeholder="Type your username..." class="inputs">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

GroupProject/GroupProject/Pages/Logout.cshtml
@page
@model MediaBazaarWebsite.Pages.LogoutModel
@{
}

GroupProject/GroupProject/Pages/Shifts.cshtml
@page
@using DataItems.LogicItems;
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Text.RegularExpressions
@model Shifts
@{
    Layout = "Shared/_LoginLayout";
}

@functions {
    public string FormatShiftType(ShiftType shiftType)
    {
        string formattedName = shiftType.ToString();
        // Add a space before "Morning", "Afternoon", or "Evening"
        formattedName = Regex.Replace(formattedName, "(Morning|Afternoon|Evening)", " $1");

        // Replace "Morning", "Afternoon", "Evening" with "Late Morning", "Late Afternoon", "Late Evening"
        if (!formattedName.StartsWith("Early"))
        {
            formattedName = "Late " + formattedName;
        }

        return formattedName;
    }
}

<div class="login">
    <video autoplay loop muted class="bg-video">
        <source src="assets/media/login/background.mp4" type="video/mp4">
    </video>
    <section class="login text-center">
        <div class="container">
            <div class="login-block">
                <div style="margin-top: -15px;" class="login-content">
                    <h2 class="mt-3 section-title">
                        <img src="assets/media/Calendar.png" alt="Calendar Icon" class="section-icon"> Your Shifts:
                    </h2>
                    <p class="date-range-label">Shifts for the week of @Model.NewDate.AddDays(0 - (int)Model.NewDate.DayOfWeek + 1).ToShortDateString() - @Model.NewDate.AddDays(6 - (int)Model.NewDate.DayOfWeek + 1).ToShortDateString()</p>

                    <hr class="section-divider">

                    <div class="calendar">
                        <div class="calendar-header">
                            <div class="calendar-header-item shift-type">Shift Type</div>
                            @for (int dayIndex = 0; dayIndex < Model.WeekDays.Count; dayIndex++)
                            {
                                var day = Model.WeekDays[dayIndex];
                                var date = Model.NewDate.AddDays(dayIndex - (int)Model.NewDate.DayOfWeek + 1);
                                <div class="calendar-header-item @(date.Date == DateTime.Today ? "current-day" : "")">
                                    @day<br />@date.ToString("dd-MM-yyyy")
                                </div>
                            }
                        </div>

                        <div class="calendar-content">
                            @foreach (var shiftType in Enum.GetValues(typeof(ShiftType)).Cast<ShiftType>().OrderBy(st => !st.ToString().StartsWith("Early")))
                            {
                                <div class="calendar-row">
                                    <div class="calendar-day shift-type">@FormatShiftType(shiftType)</div>
                                    @for (int dayIndex = 0; dayIndex < Model.WeekDays.Count; dayIndex++)
                                    {
                                        bool working = Model._assignedShifts.Any(shift =>
                                        shift.Date == Model.NewDate.AddDays(dayIndex - (int)Model.NewDate.DayOfWeek + 1) &&
                                        shift.Type == (int)shiftType);
                                        <div class="calendar-day @(working ? "working" : "not-working")">
                                            @((working ? "Working" : "Not Working"))
                                        </div>
                                    }
                                </div>
                            }
                        </div>
                    </div>

                    <div style="margin-top:15px"class="shift-navigation-buttons">
                        <form method="post">
                            <button class="btn" asp-page-handler="PreviousWeek">PAST WEEK</button>
                            <button class="btn" asp-page-handler="CurrentWeek">CURRENT WEEK</button>
                            <button class="btn" asp-page-handler="NextWeek">FUTURE WEEK</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

GroupProject/GroupProject/Pages/Vacations.cshtml
@page
@model MediaBazaarWebsite.Pages.CancelledShiftsModel
@{
	Layout = "Shared/_LoginLayout";
}

<!--=====================================-->
<!--=        login Area Start          =-->
<!--=====================================-->
<div class="login">
	<video autoplay loop muted class="bg-video">
		<source src="assets/media/login/background.mp4" type="video/mp4">
	</video>
	<section class="login text-center">
		<div class="container">
			<div class="login-block">
				<div style="margin-top: 30px;" class="login-content">
					<h2 class="mt-3 section-title">
						<img src="assets/media/Vacations.png" alt="Vacation Icon" class="section-icon"> Your Vacations:
					</h2>
					<hr class="section-divider">
					<div class="calendar">
						<div class="calendar-header">
							<!-- COLUMNS -->
							<div class="calendar-header-item-custom">Start Date</div>
							<div class="calendar-header-item-custom">End Date</div>
							<div class="calendar-header-item-custom">Reason</div>
							<div class="calendar-header-item-custom">Status</div>
						</div>

						<div class="calendar-content">
							<!-- DUMMY ROWS -->
							@foreach(var vacation in Model.vacations)
							{
								<div class="calendar-row">


									<div class="calendar-day-custom shift-type">@vacation.StartDate</div>
									<div class="calendar-day-custom">@vacation.EndDate</div>
									<div class="calendar-day-custom">@vacation.Reason</div>
									@if (vacation.Approved)
									{
										<div class="calendar-day-custom viewed">Approved</div>
									}
									else if(vacation.Pending)
									{
										<div class="calendar-day-custom sent">Pending</div>
									}
									else
									{
										<div class="calendar-day-custom rejected">Rejected</div>
									}
								</div>
							}
						</div>
					</div>

					<div class="shift-navigation-buttons">
						<!-- Dropdown for Date -->
						<div class="dropdown" style="position: relative;">
							<button class="btn" type="button" id="dropdownDate" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="position: relative; padding-right: 30px;">
								Start Date <span style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%);">&blacktriangledown;</span>
							</button>
							<div class="dropdown-menu" aria-labelledby="dropdownDate" style="margin-top: 5px; background: rgba(255, 255, 255, 0.1); color: white;">
								<form method="post">
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="StartAscending" style="font-size: 0.8rem; color: white;">Start Date Ascending</button>
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="StartDescending" style="font-size: 0.8rem; color: white;">Start Date Descending</button>
								</form>
							</div>
						</div>

						<!-- Dropdown for Status -->
						<div class="dropdown" style="position: relative;">
							<button class="btn" type="button" id="dropdownStatus" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="position: relative; padding-right: 30px;">
								End Date <span style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%);">&blacktriangledown;</span>
							</button>
							<div class="dropdown-menu" aria-labelledby="dropdownStatus" style="margin-top: 5px; background: rgba(255, 255, 255, 0.1); color: white;">
								<form method="post">
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="EndAscending" style="font-size: 0.8rem; color: white;">End Date Ascending</button>
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="StartDescending" style="font-size: 0.8rem; color: white;">End Date Descending</button>
								</form>
							</div>
						</div>

						<div class="dropdown" style="position: relative;">
							<button class="btn" type="button" id="dropdownStatus" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="position: relative; padding-right: 30px;">
								Status <span style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%);">&blacktriangledown;</span>
							</button>
							<div class="dropdown-menu" aria-labelledby="dropdownStatus" style="margin-top: 5px; background: rgba(255, 255, 255, 0.1); color: white;">
								<form method="post">
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="Approved" style="font-size: 0.8rem; color: white;">Approved</button>
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="Pending" style="font-size: 0.8rem; color: white;">Pending</button>
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="Rejected" style="font-size: 0.8rem; color: white;">Rejected</button>
									<button class="dropdown-item" asp-page-handler="Filter" asp-route-filter="AllVacations" style="font-size: 0.8rem; color: white;">All</button>
								</form>
							</div>
						</div>
						<!-- Button for Clear Filters -->
						<form method="post">
							<button class="btn" asp-page-handler="Filter" asp-route-filter="ClearVacations" style="border: 1px solid var(--color-grey-light);">Clear Filters</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>